#!/bin/bash

get_connected_usb_devices() {
    for dev in /sys/block/*; do
        props=$(udevadm info --query=property --name="${dev##*/}" 2>/dev/null)
        if echo "$props" | grep -q "ID_BUS=usb"; then
            echo "$props" | grep -E "ID_VENDOR=|ID_MODEL=|ID_SERIAL=" | tr '\n' ' '
            echo
        fi
    done
}

initial_devices=$(get_connected_usb_devices)
echo "$initial_devices"
while true; do
    current_devices=$(get_connected_usb_devices)

    if [[ "$current_devices" != "$initial_devices" ]]; then
        # Custom commands to execute
        slock
        break
    fi
    sleep 2
done
